### ISSUE TITLE
Ring compile issue

### ISSUE THREAD

**Issue by mikart143** [SergioBenitez/Rocket#1266]
Hello!
I am trying to use Rocket in my program.
I created pure project with cargo init and added rocket 0.4.4
During run or debug I am getting error: error: failed to run custom build command for `ring v0.13.5`
Basic info:
rust - 1.44 nightly
windows 10 with 2004 update
CLion with Rust plugin and VisualStudio Toolchain and WSL Toolchain
I am using rust nightly-x86_64-pc-windows-gnu

Detailed error:
```
C:/Users/mikar/.cargo/bin/cargo.exe run --color=always --package backend --bin backend
   Compiling ring v0.13.5
   Compiling http-body v0.3.1
   Compiling serde v1.0.106
   Compiling winapi v0.3.8
error: failed to run custom build command for `ring v0.13.5`

Caused by:
  process didn't exit successfully: `C:\Users\mikar\OneDrive\Dokumenty\Studia\Semestr VI\Techniki Multimedialne\Projekt\backend\target\debug\build\ring-b83c93951b62e63b\build-script-build` (exit code: 101)
--- stdout
=::: ::\
ALLUSERSPROFILE: C:\ProgramData
APPDATA: C:\Users\mikar\AppData\Roaming
CARGO: \\?\C:\Users\mikar\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\bin\cargo.exe
CARGO_CFG_TARGET_ARCH: x86_64
CARGO_CFG_TARGET_ENDIAN: little
CARGO_CFG_TARGET_ENV: gnu
CARGO_CFG_TARGET_FAMILY: windows
CARGO_CFG_TARGET_FEATURE: fxsr,mmx,sse,sse2
CARGO_CFG_TARGET_HAS_ATOMIC: 16,32,64,8,ptr
CARGO_CFG_TARGET_HAS_ATOMIC_LOAD_STORE: 16,32,64,8,ptr
CARGO_CFG_TARGET_OS: windows
CARGO_CFG_TARGET_POINTER_WIDTH: 64
CARGO_CFG_TARGET_VENDOR: pc
CARGO_CFG_WINDOWS: 
CARGO_FEATURE_DEFAULT: 1
CARGO_FEATURE_DEV_URANDOM_FALLBACK: 1
CARGO_FEATURE_USE_HEAP: 1
CARGO_HOME: C:\Users\mikar\.cargo
CARGO_MAKEFLAGS: --jobserver-fds=__rust_jobserver_semaphore_341851585 --jobserver-auth=__rust_jobserver_semaphore_341851585
CARGO_MANIFEST_DIR: C:\Users\mikar\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.13.5
CARGO_MANIFEST_LINKS: ring-asm
CARGO_PKG_AUTHORS: Brian Smith <brian@briansmith.org>
CARGO_PKG_DESCRIPTION: Safe, fast, small crypto using Rust.
CARGO_PKG_HOMEPAGE: 
CARGO_PKG_NAME: ring
CARGO_PKG_REPOSITORY: https://github.com/briansmith/ring
CARGO_PKG_VERSION: 0.13.5
CARGO_PKG_VERSION_MAJOR: 0
CARGO_PKG_VERSION_MINOR: 13
CARGO_PKG_VERSION_PATCH: 5
CARGO_PKG_VERSION_PRE: 
CHOCOLATEYINSTALL: C:\ProgramData\chocolatey
CHOCOLATEYLASTPATHUPDATE: 132278958441389314
COMMONPROGRAMFILES: C:\Program Files\Common Files
COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432: C:\Program Files\Common Files
COMPUTERNAME: DESKTOP-JR7AQSE
COMSPEC: C:\WINDOWS\system32\cmd.exe
DEBUG: true
DRIVERDATA: C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING: Default
HOMEDRIVE: C:
HOMEPATH: \Users\mikar
HOST: x86_64-pc-windows-gnu
IDEA_INITIAL_DIRECTORY: C:\WINDOWS\system32
JAVA_HOME: C:\Program Files\AdoptOpenJDK\jdk-14.0.0.36-hotspot\
LD_LIBRARY_PATH: C:\Users\mikar\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib
LOCALAPPDATA: C:\Users\mikar\AppData\Local
LOGONSERVER: \\DESKTOP-JR7AQSE
NUMBER_OF_PROCESSORS: 4
NUM_JOBS: 4
ONEDRIVE: C:\Users\mikar\OneDrive
ONEDRIVECONSUMER: C:\Users\mikar\OneDrive
OPT_LEVEL: 0
OS: Windows_NT
OUT_DIR: C:\Users\mikar\OneDrive\Dokumenty\Studia\Semestr VI\Techniki Multimedialne\Projekt\backend\target\debug\build\ring-abd4a7cceda37721\out
PATH: C:\Users\mikar\OneDrive\Dokumenty\Studia\Semestr VI\Techniki Multimedialne\Projekt\backend\target\debug\deps;C:\Users\mikar\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\bin;C:\Users\mikar\.cargo\bin;C:\Users\mikar\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\bin;C:\Program Files\AdoptOpenJDK\jdk-14.0.0.36-hotspot\bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\ArchestrA\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\Oracle\VirtualBox;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Seq\;C:\Program Files\Seq\Client\;C:\Program Files\Wasmtime\bin;C:\Program Files\dotnet\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\mikar\.cargo\bin;C:\Program Files\AdoptOpenJDK\jdk-14.0.0.36-hotspot\bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\ArchestrA\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\Oracle\VirtualBox;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Seq\;C:\Program Files\Seq\Client\;C:\Program Files\Wasmtime\bin;C:\Program Files\dotnet\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;;C:\Users\mikar\.dotnet\tools;C:\Users\mikar\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Wasmtime\bin
PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE: AMD64
PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
PROCESSOR_LEVEL: 6
PROCESSOR_REVISION: 9e09
PROFILE: debug
PROGRAMDATA: C:\ProgramData
PROGRAMFILES: C:\Program Files
PROGRAMFILES(X86): C:\Program Files (x86)
PROGRAMW6432: C:\Program Files
PSMODULEPATH: C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC: C:\Users\Public
RUSTC: rustc
RUSTDOC: rustdoc
RUSTUP_HOME: C:\Users\mikar\.rustup
RUSTUP_TOOLCHAIN: nightly-x86_64-pc-windows-gnu
RUST_BACKTRACE: short
RUST_RECURSION_COUNT: 1
SESSIONNAME: Console
SYSTEMDRIVE: C:
SYSTEMROOT: C:\WINDOWS
TARGET: x86_64-pc-windows-gnu
TEMP: C:\Users\mikar\AppData\Local\Temp
TERM: ansi
TMP: C:\Users\mikar\AppData\Local\Temp
USERDOMAIN: DESKTOP-JR7AQSE
USERDOMAIN_ROAMINGPROFILE: DESKTOP-JR7AQSE
USERNAME: mikar
USERPROFILE: C:\Users\mikar
VBOX_MSI_INSTALL_PATH: C:\Program Files\Oracle\VirtualBox\
WINDIR: C:\WINDOWS
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
running "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wmissing-prototypes" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-Wno-cast-align" "-g3" "-D_XOPEN_SOURCE=700" "-c" "-oC:\\Users\\mikar\\OneDrive\\Dokumenty\\Studia\\Semestr VI\\Techniki Multimedialne\\Projekt\\backend\\target\\debug\\build\\ring-abd4a7cceda37721\\out\\aes.o" "crypto/fipsmodule/aes/aes.c"

--- stderr
thread 'main' panicked at 'failed to execute ["gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wmissing-prototypes" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-Wno-cast-align" "-g3" "-D_XOPEN_SOURCE=700" "-c" "-oC:\\Users\\mikar\\OneDrive\\Dokumenty\\Studia\\Semestr VI\\Techniki Multimedialne\\Projekt\\backend\\target\\debug\\build\\ring-abd4a7cceda37721\\out\\aes.o" "crypto/fipsmodule/aes/aes.c"]: The system cannot find the file specified. (os error 2)', C:\Users\mikar\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.13.5\build.rs:642:9
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:59
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:511
  11: rust_begin_unwind
             at src\libstd/panicking.rs:419
  12: std::panicking::begin_panic_fmt
             at src\libstd/panicking.rs:373
  13: build_script_build::run_command::{{closure}}
             at .\build.rs:642
  14: core::result::Result<T,E>::unwrap_or_else
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libcore/result.rs:851
  15: build_script_build::run_command
             at .\build.rs:641
  16: build_script_build::compile
             at .\build.rs:522
  17: build_script_build::build_library::{{closure}}
             at .\build.rs:460
  18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libcore\ops/function.rs:285
  19: core::option::Option<T>::map
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libcore/option.rs:456
  20: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libcore\iter\adapters/mod.rs:803
  21: alloc::vec::Vec<T>::extend_desugared
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\liballoc/vec.rs:2138
  22: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\liballoc/vec.rs:2031
  23: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\liballoc/vec.rs:2026
  24: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\liballoc/vec.rs:1926
  25: core::iter::traits::iterator::Iterator::collect
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libcore\iter\traits/iterator.rs:1659
  26: build_script_build::build_library
             at .\build.rs:456
  27: build_script_build::build_c_code::{{closure}}
             at .\build.rs:433
  28: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libcore\iter\traits/iterator.rs:655
  29: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libcore\iter\traits/iterator.rs:2001
  30: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libcore\iter\traits/iterator.rs:1877
  31: core::iter::traits::iterator::Iterator::fold
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libcore\iter\traits/iterator.rs:2004
  32: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libcore\iter\traits/iterator.rs:658
  33: build_script_build::build_c_code
             at .\build.rs:431
  34: build_script_build::ring_build_rs_main
             at .\build.rs:301
  35: build_script_build::main
             at .\build.rs:263
  36: std::rt::lang_start::{{closure}}
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libstd/rt.rs:67
  37: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:52
  38: std::panicking::try::do_call
             at src\libstd/panicking.rs:331
  39: std::panicking::try
             at src\libstd/panicking.rs:274
  40: std::panic::catch_unwind
             at src\libstd/panic.rs:394
  41: std::rt::lang_start_internal
             at src\libstd/rt.rs:51
  42: std::rt::lang_start
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libstd/rt.rs:67
  43: main
  44: _tmainCRTStartup
  45: mainCRTStartup
  46: unit_addrs_search
  47: unit_addrs_search
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

Process finished with exit code 101
```

**Comment by jebrosen** [comment]
First, if you do not plan to use private cookies you can disable them, which will remove the dependency on ring:

```toml
[dependencies]
rocket = { version = "0.4", default-features = false }
```

`ring` tends to have better support for the MSVC target, so I would try one of these first if you do need private cookies:

* Install the MSVC tools from Microsoft's website and the `x86_64-pc-windows-msvc` toolchain via `rustup`
* Compile/run in WSL only

**Comment by mikart143** [comment]
Thanks!
I simply changed to msvc. I will check ring repo for further info :D

**Comment by jebrosen** [comment]
If you do want to use the `-gnu` target, you will have to install MinGW and add it to your `PATH` so that the build script can find it.

It's worth noting that ring `0.13` is not maintained and `-gnu` is a secondary target, so you will probably not get much in the way of support if you still have issues. Unfortunately we are nervous about trying to upgrade the ring version until Rocket 0.5; see also #1016.
