### ISSUE TITLE
Rust-postgres refuses to connect on simple fairing, exiting with code 24

### ISSUE THREAD

**Issue by 0x6861796169** [SergioBenitez/Rocket#2134]
**Description**

I am attempting to write an application that uses the `postgres::Client` poolable type, but when I run a very basic setup with no logic whatsoever, just setting up the connection, it gives me this obscure error:

```
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
thread 'r2d2-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
thread 'r2d2-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /Users/sayakhxro/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.19.2/src/config.rs:342:14
```

**To Reproduce**

Cargo.toml

```TOML
[package]
name = "test-rocket-postgres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.2"
rocket = "0.5.0-rc.1"

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
default-features = false
features = ["postgres_pool"]
```

Main.rs
```Rust
#[macro_use]
extern crate rocket;

use rocket_sync_db_pools::{database, postgres};

#[database("test_db")]
pub struct TestDbConn(postgres::Client);

#[get("/")]
pub async fn main_route(conn: TestDbConn) {}

#[rocket::main]
async fn main() {
    rocket::build()
        .attach(TestDbConn::fairing())
        .mount("/", routes![main_route])
        .launch()
        .await
        .unwrap();
}
```

**Expected Behavior**

I would expect a successful connection, and a database fairing to be created with a thread pool

**Environment:**

 - OS Distribution and Kernel: macOS 11.4
 - Rocket Version: 0.1.0-rc.1

**Comment by dawid-nowak** [comment]
@0x6861796169 I have re-run your code on Linux Ubuntu and it works as expected. It looks like your problem is more to do with open file handlers than Rocket. Have you looked into increasing the limit for open files for example ulimit -n 10240??

**Comment by SergioBenitez** [comment]
Indeed, this is a file limit issue. See @dawid-nowak's comment.
