### ISSUE TITLE
How to pattern match rocket::http::Status?

### ISSUE THREAD

**Issue by vvilhonen** [SergioBenitez/Rocket#530]
Getting the following compiler crash when attempting to pattern match a Status. Equality comparison with `if` seems to work though.

```rust
match Status::Ok {
  Status::Ok => println!("OK"),
  _ => ()
};
```

```
   Compiling fairings v0.0.0 (file:///home/user/work/Rocket/examples/fairings)
error: internal compiler error: librustc_const_eval/_match.rs:261: bad constructor ConstantValue(Const { ty: rocket::http::Status, val: Aggregate(Struct([(code, Const { ty: u16, val: Integral(U16(200)) }), (reason, Const { ty: &'static str, val: Str("OK") })])) }) for adt rocket::http::Status

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-nightly (6828cf901 2018-01-06) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:504:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:381
   3: std::panicking::default_hook
             at libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::bug
   7: <std::thread::local::LocalKey<T>>::with
   8: rustc::ty::context::tls::with_opt
   9: rustc::session::opt_span_bug_fmt
  10: rustc::session::bug_fmt
  11: rustc_const_eval::_match::Constructor::variant_index_for_adt
  12: rustc_const_eval::_match::constructor_sub_pattern_tys
  13: rustc_const_eval::_match::is_useful_specialized
  14: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::try_fold
  15: rustc_const_eval::_match::is_useful
  16: rustc_const_eval::check_match::check_arms
  17: rustc_const_eval::_match::MatchCheckCtxt::create_and_enter
  18: <rustc_const_eval::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  19: rustc::hir::intravisit::walk_expr
  20: <rustc_const_eval::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  21: <rustc_const_eval::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  22: rustc::session::Session::track_errors
  23: rustc_const_eval::check_match::check_match
  24: rustc::dep_graph::graph::DepGraph::with_task_impl
  25: rustc_errors::Handler::track_diagnostics
  26: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  27: rustc::ty::maps::<impl rustc::ty::maps::queries::check_match<'tcx>>::force
  28: rustc::ty::maps::<impl rustc::ty::maps::queries::check_match<'tcx>>::try_get
  29: rustc::ty::maps::TyCtxtAt::check_match
  30: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::check_match
  31: rustc::hir::intravisit::Visitor::visit_nested_body
  32: rustc::hir::Crate::visit_all_item_likes
  33: rustc_const_eval::check_match::check_crate
  34: <std::thread::local::LocalKey<T>>::with
  35: <std::thread::local::LocalKey<T>>::with
  36: rustc::ty::context::TyCtxt::create_and_enter
  37: rustc_driver::driver::compile_input
  38: rustc_driver::run_compiler

error: Could not compile `fairings`.

To learn more, run the command again with --verbose.
```

Tried with `0.3.5` and the current `master`. Rust versions `nightly-2017-12-21-x86_64-unknown-linux-gnu` and `nightly-2018-01-06-x86_64-unknown-linux-gnu`.

**Comment by SergioBenitez** [comment]
This is https://github.com/rust-lang/rust/issues/46114.
